name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  cmake:
    name: Prepares the make files
    runs-on: ubuntu-latest
    steps:
      - name: Requirements
        shell: bash
        run: apt install cmake g++ doxygen default-jre #imagemagick

      - name: Checkout repo
        uses: actions/checkout@1.0.0

      - name: Create and go to build folder
        run: mkdir -p build

      - name: Run cmake in build
        run: cd build && cmake ..

  make:
    name: Builds executables
    needs: cmake
    runs-on: ubuntu-latest
    steps:
      - name: Requirements
        shell: bash
        run: apt install g++ default-jre

      - name: Run make for ALL
        run: cd build && make

  makedocs:
    name: Deploy the documentation pages
    needs: cmake
    runs-on: ubuntu-latest
    steps:
    - name: Requirements
      run: apt install doxygen
        # && apt install sphinx-doc
        # && pip3 install sphinx-rtd-theme
        # && pip3 install breathe
        # && pip3 install sphinx-sitemap

    # - name: Checkout repo
    #   uses: actions/checkout@1.0.0

    - name: Build docs
      run: cd build
        && cmake ..
        && make doxygen
        # && cd docs/doxygen/html
        # && touch .nojekyll
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/docs/doxygen/html # The folder the action should deploy.